= Welcome to the ownCloud Quickstart Guide! 

*ownCloud* is the flexible open source file synchronization and sharing solution, which runs on Linux and has client applications for Linux, Windows, and macOS, as well as mobile apps for Android and iOS. 

This Quickstart guide will help you install and configure an Owncloud 10.0.10 server and perform some common administrative tasks. We assume you are familiar with downloading, installing, and configuring Linux applications and the associated https://en.wikipedia.org/wiki/LAMP_(software_bundle)[LAMP] (*Linux/Apache/MySQL/PHP*) stack necessary to provide a web-based service.

The guide is divided into a number of sections that will step you through a basic installation, suitable for learning how to use ownCloud, or setting it up for a small workgroup.  

- Section 1 describes link:owncloud_qs_s1.html[system requirements and deployment recommendations].
- Section 2 explains link:owncloud_qs_s2.html[installation with the Linux Package Manager].
- Section 3 covers link:owncloud_qs_s3.html[configuration of the installed system].
- Section 4 covers some link:owncloud_qs_s4.html[common administrative tasks].
- Section 5 describes how a user connects to the ownCloud server link:owncloud_qs_s5.html[using a desktop or mobile client]. 

To learn more about ownCloud, go to the https://doc.owncloud.org/server/administration_manual/index.html[ownCloud Server Administration Guide], which provides comprehensive information for users who want to install, administer, and optimize their ownCloud servers.

To learn more about ownCloud as an end user, go to the https://doc.owncloud.org/server/10.0/user_manual/[ownCloud User Manual]. This provides details of the ownCloud Desktop Client, and the Android and iOS mobile apps.

==== Let's get started by checking link:owncloud_qs_s1.html[System Requirements]
